language: python

python:
    - "3.4"
    - "3.6"

install:
    - pip install flake8 cpplint

script:
    - flake8
    - cpplint --quiet --recursive --filter="-legal/copyright,-runtime/int,-runtime/arrays" .

notifications:
    email: false
